//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ADT.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ADT_DIALOG                  102
#define IDS_CONNECT                     102
#define IDS_DISCONNECT                  103
#define IDS_ERR0005                     104
#define IDS_ERR0002                     105
#define IDS_APPTITLE                    106
#define IDR_MAINFRAME                   128
#define IDS_ADT_SENDFILE                200
#define IDS_ADT_CANTOPEN                201
#define IDS_ADT_NOT140K                 202
#define IDS_ADT_BADHEADER               203
#define IDS_ADT_CRCERR                  204
#define IDS_ADT_RECEIVE_FILE            205
#define IDS_ADT_EXISTS                  206
#define IDS_ADT_DISKFULL                207
#define IDS_ADT_READY                   208
#define IDC_PROGRESS1                   1001
#define IDC_CONNECT                     1002
#define IDC_BUTTON2                     1003
#define IDC_PROGRESS2                   1004
#define IDC_STATUS                      1005
#define IDC_PROGRESS3                   1006
#define IDC_PROGRESS4                   1007
#define IDC_PROGRESS5                   1008
#define IDC_COMBO_PORT                  1010
#define IDC_COMBO_SPEED                 1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
